### ISSUE TITLE
Test with Heri II not working, possible installation issue

### ISSUE THREAD

**Issue by edoardolamon** [ADVRHumanoids/ROSEndEffectorPackageManager#1]
Hi guys, I have tried to install your package and test it with the two launch files for the Heri II, as explained in the documentation, and I'm getting few errors. 

1. In the launch for the online phase the joint state publisher crashes.
```bash
edoardo@vision-ZBOX-EN1080-1080K:~$ roslaunch ros_end_effector rosee_startup.launch hand_name:=heri_II
... logging to /home/edoardo/.ros/log/70101d06-8b0d-11ea-afc2-0c5415a36088/roslaunch-vision-ZBOX-EN1080-1080K-16786.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vision-ZBOX-EN1080-1080K:37813/

SUMMARY
========

PARAMETERS
 * /joint_state_publisher/source_list: ['ros_end_effecto...
 * /joint_state_publisher/use_gui: False
 * /rate: 100.0
 * /robot_state_publisher/publish_frequency: 200.0
 * /ros_ee_config_path: /home/edoardo/cat...
 * /rosdistro: kinetic
 * /rosee/joint_states_topic: /js_publisher/joi...
 * /rosversion: 1.12.14

NODES
  /
    UniversalRosEndEffector (ros_end_effector/UniversalRosEndEffector)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [16796]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 70101d06-8b0d-11ea-afc2-0c5415a36088
process[rosout-1]: started with pid [16809]
started core service [/rosout]
process[UniversalRosEndEffector-2]: started with pid [16822]
process[joint_state_publisher-3]: started with pid [16827]
[ INFO] [1588270042.588733981]: ROSEndEffector Parser found URDF path: /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/include/ROSEndEffector/../..//configs/urdf/heri_II.urdf
[ INFO] [1588270042.588823545]: ROSEndEffector Parser found SRDF path: /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/include/ROSEndEffector/../..//configs/srdf/heri_II.srdf
process[robot_state_publisher-4]: started with pid [16835]
[ INFO] [1588270042.590535464]: ROSEndEffector Parser found end_effector: heri_hand_end_effector
[ INFO] [1588270042.590607571]: ROSEndEffector Parser found group: end_effector_fingers in the SRDF with the following fingers: 
[ INFO] [1588270042.590626622]: finger_1
[ INFO] [1588270042.590636540]: finger_2
[ INFO] [1588270042.590646983]: finger_3
[ INFO] [1588270042.590655615]: thumb
[ INFO] [1588270042.590971444]: ROSEndEffector Parser successfully configured using config file:  /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/configs/heri_II.yaml
[ INFO] [1588270042.590987716]: ROS End Effector: Finger Joints Map
[ INFO] [1588270042.590998974]: -------------------------
[ INFO] [1588270042.591013924]: finger_1
[ INFO] [1588270042.591026233]: LFB1__LFP1_1
[ INFO] [1588270042.591034735]: LFP1_1__LFP1_2
[ INFO] [1588270042.591042873]: LFP1_2__LFP1_3
[ INFO] [1588270042.591051828]: -------------------------
[ INFO] [1588270042.591061182]: finger_2
[ INFO] [1588270042.591069370]: LFB2__LFP2_1
[ INFO] [1588270042.591077396]: LFP2_1__LFP2_2
[ INFO] [1588270042.591085364]: LFP2_2__LFP2_3
[ INFO] [1588270042.591093541]: -------------------------
[ INFO] [1588270042.591101761]: finger_3
[ INFO] [1588270042.591109823]: LFB3__LFP3_1
[ INFO] [1588270042.591117719]: LFP3_1__LFP3_2
[ INFO] [1588270042.591125759]: LFP3_2__LFP3_3
[ INFO] [1588270042.591133789]: -------------------------
[ INFO] [1588270042.591142735]: thumb
[ INFO] [1588270042.591150860]: SFB1__SFP1_1
[ INFO] [1588270042.591158771]: SFP1_1__SFP1_2
[ INFO] [1588270042.591166726]: -------------------------
[ERROR] [1588270042.591461651]: [setParam] Failed to contact master at [localhost:11311].  Retrying...
process[rviz-5]: started with pid [16840]
[ERROR] [1588270042.604622906]: Could not find parameter robot_description on parameter server
[ INFO] [1588270042.643709747]: Connected to master at [localhost:11311]
[ INFO] [1588270042.644746882]: Set urdf and srdf file in the param server from config file 
[ INFO] [1588270042.645004651]: Fingers in EEInterface: 
[ INFO] [1588270042.645023823]: finger_1
[ INFO] [1588270042.645038356]: finger_2
[ INFO] [1588270042.645051458]: finger_3
[ INFO] [1588270042.645065101]: thumb
[ERROR getFilesInDir] pathFolder/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/include/ROSEndEffector/../..//configs/actions/heri_II/timeds/ does not exists
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name tipFlex
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name fingFlex
[ INFO] [1588270042.649097955]: PINCHES-TIGHT:
ActionName: pinchTight
FingersInvolved: [LFP2_3, SFP1_2]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

Action_State_1 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.480754
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.450186
	MoveitContact:
		body_name_1: LFP2_3
		body_name_2: SFP1_2
		body_type_1: 0
		body_type_2: 0
		depth: 0.000547616
		normal: [-0.0169706, -0.596905, -0.802133]
		pos: [-0.0115241, -0.0143068, 0.209554]
Action_State_2 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.47917
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.461391
	MoveitContact:
		body_name_1: LFP2_3
		body_name_2: SFP1_2
		body_type_1: 0
		body_type_2: 0
		depth: 0.000509984
		normal: [-0.0169705, -0.60071, -0.799287]
		pos: [-0.0115241, -0.0133044, 0.20906]
Action_State_3 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.495338
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.443662
	MoveitContact:
		body_name_1: SFP1_2
		body_name_2: LFP2_3
		body_type_1: 0
		body_type_2: 0
		depth: 0.000380034
		normal: [2.91305e-06, 0.232011, 0.972713]
		pos: [-0.00911732, -0.0119186, 0.205366]

[ INFO] [1588270042.649297280]: PINCHES-LOOSE:
[ INFO] [1588270042.649316054]: TRIGGERS:
ActionName: trig
FingersInvolved: [LFP1_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 1
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0.5
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [LFP2_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.5
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [LFP3_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 1
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0.5
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [SFP1_2]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.5


[ INFO] [1588270042.649457174]: TIP FLEX:
[ INFO] [1588270042.649473667]: FINGER FLEX:
[ INFO] [1588270042.649502668]: GRASP:
Composed Action 'grasp' (independent):
Composed by 4 inner action: [trig, trig, trig, trig]
Fingers involved: [LFP1_3, LFP2_3, LFP3_3, SFP1_2]
Each joint influenced by x inner action:
	LFB1__LFP1_1 : 1
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 1
	SFB1__SFP1_1 : 1
JointPos:
		LFB1__LFP1_1 : 0.5
		LFB2__LFP2_1 : 0.5
		LFB3__LFP3_1 : 0.5
		SFB1__SFP1_1 : 0.5

[ INFO] [1588270042.659778784]: Getting joint pos from '/js_publisher/joint_states'
[ INFO] [1588270042.661992384]: Started looping @ 100Hz
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 44, in <module>
    jsp = joint_state_publisher.JointStatePublisher()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/joint_state_publisher/__init__.py", line 145, in __init__
    raise RuntimeError('The robot_description parameter is required and not set.')
RuntimeError: The robot_description parameter is required and not set.
[robot_state_publisher-4] process has died [pid 16835, exit code 255, cmd /opt/ros/kinetic/lib/robot_state_publisher/robot_state_publisher joint_states:=/js_publisher/joint_states __name:=robot_state_publisher __log:=/home/edoardo/.ros/log/70101d06-8b0d-11ea-afc2-0c5415a36088/robot_state_publisher-4.log].
log file: /home/edoardo/.ros/log/70101d06-8b0d-11ea-afc2-0c5415a36088/robot_state_publisher-4*.log
[joint_state_publisher-3] process has died [pid 16827, exit code 1, cmd /opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher joint_states:=/js_publisher/joint_states __name:=joint_state_publisher __log:=/home/edoardo/.ros/log/70101d06-8b0d-11ea-afc2-0c5415a36088/joint_state_publisher-3.log].
log file: /home/edoardo/.ros/log/70101d06-8b0d-11ea-afc2-0c5415a36088/joint_state_publisher-3*.log

```

2. For the offline phase I'm getting some warnings about parameters not set:
```bash
edoardo@vision-ZBOX-EN1080-1080K:~$ roslaunch ros_end_effector findActions.launch hand_name:=heri_II
... logging to /home/edoardo/.ros/log/594ec19e-8b0d-11ea-afc2-0c5415a36088/roslaunch-vision-ZBOX-EN1080-1080K-16481.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vision-ZBOX-EN1080-1080K:39969/

SUMMARY
========

PARAMETERS
 * /ros_ee_config_path: /home/edoardo/cat...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    UniversalFindActions (ros_end_effector/UniversalFindActions)

auto-starting new master
process[master]: started with pid [16492]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 594ec19e-8b0d-11ea-afc2-0c5415a36088
process[rosout-1]: started with pid [16505]
started core service [/rosout]
process[UniversalFindActions-2]: started with pid [16508]
[ INFO] [1588270004.440266355]: ROSEndEffector Parser found URDF path: /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/include/ROSEndEffector/../..//configs/urdf/heri_II.urdf
[ INFO] [1588270004.440319270]: ROSEndEffector Parser found SRDF path: /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/include/ROSEndEffector/../..//configs/srdf/heri_II.srdf
[ INFO] [1588270004.442109950]: ROSEndEffector Parser found end_effector: heri_hand_end_effector
[ INFO] [1588270004.442155787]: ROSEndEffector Parser found group: end_effector_fingers in the SRDF with the following fingers: 
[ INFO] [1588270004.442180370]: finger_1
[ INFO] [1588270004.442188863]: finger_2
[ INFO] [1588270004.442195174]: finger_3
[ INFO] [1588270004.442205606]: thumb
[ INFO] [1588270004.442481879]: ROSEndEffector Parser successfully configured using config file:  /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/configs/heri_II.yaml
[ERROR] [1588270004.442774786]: [setParam] Failed to contact master at [localhost:11311].  Retrying...
[ INFO] [1588270004.496931922]: Connected to master at [localhost:11311]
[ INFO] [1588270004.498922493]: FINDACTIONS: Set urdf and srdf file in the param server from config file /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector/configs/heri_II.yaml
[ INFO] [1588270004.505044897]: Loading robot model 'heri_II'...
[ WARN] [1588270004.505103388]: Skipping virtual joint 'virtualJointWorld' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1588270004.505125700]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1588270004.568722615]: Could not identify parent group for end-effector 'heri_hand_end_effector'
[PARSER::init]: Parsed Model: heri_II
[PARSER::lookForFingertips] Found Group 'end_effector_fingers', but it has some subgroups 

[PARSER::lookForFingertips] Found Group 'finger_1', with links: 
	'LFB1' (not a leaf link) 
	'LFP1_1' (not a leaf link) 
	'LFP1_2' (not a leaf link) 
	'LFP1_3' (a leaf link) 

[PARSER::lookForFingertips] Found Group 'finger_2', with links: 
	'LFB2' (not a leaf link) 
	'LFP2_1' (not a leaf link) 
	'LFP2_2' (not a leaf link) 
	'LFP2_3' (a leaf link) 

[PARSER::lookForFingertips] Found Group 'finger_3', with links: 
	'LFB3' (not a leaf link) 
	'LFP3_1' (not a leaf link) 
	'LFP3_2' (not a leaf link) 
	'LFP3_3' (a leaf link) 

[PARSER::lookForFingertips] Found Group 'thumb', with links: 
	'SFB1' (not a leaf link) 
	'SFB1_1' (not a leaf link) 
	'SFP1_2' (a leaf link) 

[ INFO] [1588270004.759399894]: Loading robot model 'heri_II'...
[ WARN] [1588270004.759435914]: Skipping virtual joint 'virtualJointWorld' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1588270004.759443580]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1588270004.779519262]: Could not identify parent group for end-effector 'heri_hand_end_effector'
[ WARN] [1588270004.817442775]: No kinematics plugins defined. Fill and load kinematics.yaml!
[FINDACTIONS::findPinch]: I found no loose pinches. This mean that some error happened or that all the tips pairs collide with each other for at least one hand configuration.
[FINDACTIONS::findSingleJointMultipleTips]  no singleJointMultipleTips with 3 found
[FINDACTIONS::findSingleJointMultipleTips]  no singleJointMultipleTips with 2 found
PARSED MAP OF PINCHESTIGHT FROM YAML FILE:
ActionName: pinchTight
FingersInvolved: [LFP2_3, SFP1_2]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

Action_State_1 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.480754
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.450186
	MoveitContact:
		body_name_1: LFP2_3
		body_name_2: SFP1_2
		body_type_1: 0
		body_type_2: 0
		depth: 0.000547616
		normal: [-0.0169706, -0.596905, -0.802133]
		pos: [-0.0115241, -0.0143068, 0.209554]
Action_State_2 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.47917
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.461391
	MoveitContact:
		body_name_1: LFP2_3
		body_name_2: SFP1_2
		body_type_1: 0
		body_type_2: 0
		depth: 0.000509984
		normal: [-0.0169705, -0.60071, -0.799287]
		pos: [-0.0115241, -0.0133044, 0.20906]
Action_State_3 :
	JointStates:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.495338
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.443662
	MoveitContact:
		body_name_1: SFP1_2
		body_name_2: LFP2_3
		body_type_1: 0
		body_type_2: 0
		depth: 0.000380034
		normal: [2.91305e-06, 0.232011, 0.972713]
		pos: [-0.00911732, -0.0119186, 0.205366]

PARSED MAP OF PINCHESLOOSE FROM YAML FILE:
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name pinchLoose
PARSED MAP OF TRIGS FROM YAML FILE:
ActionName: trig
FingersInvolved: [LFP1_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 1
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0.5
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [LFP2_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.5
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [LFP3_3]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 1
	SFB1__SFP1_1 : 0

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0.5
		SFB1__SFP1_1 : 0


ActionName: trig
FingersInvolved: [SFP1_2]
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 0
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.5


PARSED MAP OF TIPFLEX FROM YAML FILE:
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name tipFlex
PARSED MAP OF FINGFLEX FROM YAML FILE:
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name fingFlex
PARSED MAP OF SINGLEJOINTMULTIPLETIPS FROM YAML FILE:
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name singleJointMultipleTips_3
DEBUG MULTIPINCH PARSED: 
[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name multiplePinchTight_3
A composed action with Independent inner action: 
Composed Action 'grasp' (independent):
Composed by 4 inner action: [trig, trig, trig, trig]
Fingers involved: [LFP1_3, LFP2_3, LFP3_3, SFP1_2]
Each joint influenced by x inner action:
	LFB1__LFP1_1 : 1
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 1
	SFB1__SFP1_1 : 1
JointPos:
		LFB1__LFP1_1 : 0.5
		LFB2__LFP2_1 : 0.5
		LFB3__LFP3_1 : 0.5
		SFB1__SFP1_1 : 0.5

PARSED COMPOSEd
Composed Action 'grasp' (independent):
Composed by 4 inner action: [trig, trig, trig, trig]
Fingers involved: [LFP1_3, LFP2_3, LFP3_3, SFP1_2]
Each joint influenced by x inner action:
	LFB1__LFP1_1 : 1
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 1
	SFB1__SFP1_1 : 1
JointPos:
		LFB1__LFP1_1 : 0.5
		LFB2__LFP2_1 : 0.5
		LFB3__LFP3_1 : 0.5
		SFB1__SFP1_1 : 0.5


Casual action manually created: 
ActionName: casual
FingersInvolved: <not inserted>
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.961508
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.900372


The parsed casual: 
ActionName: casual
FingersInvolved: <not inserted>
JointsInvolvedCount: 
	LFB1__LFP1_1 : 0
	LFB2__LFP2_1 : 1
	LFB3__LFP3_1 : 0
	SFB1__SFP1_1 : 1

JointPos:
		LFB1__LFP1_1 : 0
		LFB2__LFP2_1 : 0.961508
		LFB3__LFP3_1 : 0
		SFB1__SFP1_1 : 0.900372


[ERROR MapActionHandler::getPrimitiveMap] Not found any action with name singleJointMultipleTips_3
[UniversalFindActions-2] process has finished cleanly
log file: /home/edoardo/.ros/log/594ec19e-8b0d-11ea-afc2-0c5415a36088/UniversalFindActions-2*.log
```
3. This might be due to an installation issue that I faced while running the command `rosinstall .` 
```bash
edoardo@vision-ZBOX-EN1080-1080K:~/catkin_ws/src/ROSEndEffectorPackageManager/src(devel)$ rosinstall .
rosinstall operating on /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src from specifications in rosinstall files  
(Over-)Writing /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/.rosinstall
[ROSEndEffector] Fetching https://github.com/ADVRHumanoids/ROSEndEffector.git (version devel) to /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector
Cloning into '/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/ROSEndEffector'...
remote: Enumerating objects: 423, done.
remote: Counting objects: 100% (423/423), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 13993 (delta 365), reused 363 (delta 320), pack-reused 13570
Receiving objects: 100% (13993/13993), 12.30 MiB | 6.95 MiB/s, done.
Resolving deltas: 100% (12894/12894), done.
Checking connectivity... done.
[ROSEndEffector] Done.
[roboticsgroup_gazebo_plugins] Fetching https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins.git (version None) to /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/roboticsgroup_gazebo_plugins
Cloning into '/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/roboticsgroup_gazebo_plugins'...
remote: Enumerating objects: 176, done.
remote: Total 176 (delta 0), reused 0 (delta 0), pack-reused 176
Receiving objects: 100% (176/176), 33.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (103/103), done.
Checking connectivity... done.
[roboticsgroup_gazebo_plugins] Done.
[rosee_gazebo_plugins] Fetching https://github.com/ADVRHumanoids/rosee_gazebo_plugins.git (version devel) to /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_gazebo_plugins
Cloning into '/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_gazebo_plugins'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 291 (delta 145), reused 277 (delta 132), pack-reused 0
Receiving objects: 100% (291/291), 212.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (145/145), done.
Checking connectivity... done.
[rosee_gazebo_plugins] Done.
[rosee_gui] Fetching https://github.com/ADVRHumanoids/rosee_gui.git (version devel) to /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_gui
Cloning into '/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_gui'...
remote: Enumerating objects: 201, done.
remote: Counting objects: 100% (201/201), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 201 (delta 118), reused 138 (delta 59), pack-reused 0
Receiving objects: 100% (201/201), 42.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (118/118), done.
Checking connectivity... done.
[rosee_gui] Done.
[rosee_msg] Fetching https://github.com/ADVRHumanoids/rosee_msg.git (version devel) to /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_msg
Cloning into '/home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src/rosee_msg'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 47 (delta 21), reused 35 (delta 12), pack-reused 0
Unpacking objects: 100% (47/47), done.
Checking connectivity... done.
[rosee_msg] Done.
(Over-)Writing setup.sh, setup.bash, and setup.zsh in /home/edoardo/catkin_ws/src/ROSEndEffectorPackageManager/src
ERROR in rosinstall: 
No 'ros' stack detected in candidates [].
Please add the location of a ros distribution to this command.

See http://ros.org/wiki/rosinstall.
```
4. This is just a doubt on the installation. In the documentation, after `rosinstall .`, we need to compile with `catkin_make`. Usually I perform this command inside my catkin_ws folder. Are you missing in the documentation a `cd path/to/your/catkin_ws` between `rosinstall .` and `catkin_make`?

**Comment by torydebra** [comment]
Hi, thanks for the issue and sorry if I reply only now, I wasn't watching this repo and no notifications arrived. I answer below:

> 4. This is just a doubt on the installation. In the documentation, after rosinstall ., we need to ...

Yes we forgot a `cd` , now it is present

> 3. This might be due to an installation issue that I faced while running the command rosinstall .

If you speak about this error:
~~~
ERROR in rosinstall: 
No 'ros' stack detected in candidates [].
Please add the location of a ros distribution to this command.
~~~
It does not cause any issues, I think this is caused because in truth rosinstall is not only for cloning multiple repository but it is a bigger tool. We use it only for cloning at right branches.

I will check further the first two points

**Comment by torydebra** [comment]
For the first two problems, do you have clone the last commits? Do you have the ADVRHumanoids/ROSEndEffector@e6363fecd04fa3a792314fbc961b25231a50f52c commit ?

**Comment by liesrock** [comment]
I can add that:

```
rosinstall .
```

actually updates all the branches inside each repo.

**Comment by torydebra** [comment]
It should be solved in the issues above
